### PR TITLE
Replace nmtui with nmcli

### PR DESCRIPTION
**Pull request by kivaisan**
Testing team needs `nmcli` so replacing `nmtui` with it.

### CODE REVIEW

**Comment by kivaisan** [comment]
@jannehekkala @JanneKiiskila @esajaa please review.

**Comment by JanneKiiskila** [comment]
Ok, have to admit I don't know the differences between nmtui vs. nmcli. @OPpuolitaival  @jannehekkala  - any idea? What would SyTe prefer?

**Comment by JanneKiiskila** [comment]
Ok, so you can have both.
https://www.unixarena.com/2015/04/rhel-7-network-management-nmcli-or-nmtui.html/

`nmtui` is just offering a you "text-based graphical UI" for the same things, which you can do with `nmcli`. `nmcli` is just better for scripting, which we will likely need so let's go with that one.

We could also add then `nmtui` if need be, they can co-exist.

**Comment by kivaisan** [comment]
Yes. I think nobody uses nmtui. Let's add it back if some user shows up.

**Review by OPpuolitaival — APPROVED** [review]
Looks very good!

**Review by jannehekkala — APPROVED** [review]
LGTM

**Comment by esajaa** [comment]
`nmtui` originates from the LmP `lmp-gateway-image`. It is currently replaced there already with `nmcli`. Good change 👍

**Review by esajaa — APPROVED** [review]

**Pull request merged**
