### PR TITLE
Updated edge-proxy launch script to resolve containers.local url

### PR DESCRIPTION
**Pull request by ygoyal18**

### CODE REVIEW

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by petedyerarm** [comment]
I think that the last line needs some extra parentheses:
`-forwarding-addresses={{\"gateways.local\":\"${GATEWAYS_ADDRESS#"https://"}\"},{\"containers.local\":\"${CONTAINERS_ADDRESS#"https://"}\"}}`

**Review by costanic — APPROVED** [review]

**Comment by ygoyal18** [comment]
@OPpuolitaival edge-proxy is failing to run. Looks like the previous PR #301 broke the dev build. Please investigate why PR checks are not catching this. 

```May 26 13:29:18 imx8mmevk launch-edge-proxy.sh[35410]: forwarding-addresses invalid: invalid character ':' after top-level value
May 26 13:29:18 imx8mmevk systemd[1]: edge-proxy.service: Main process exited, code=exited, status=1/FAILURE
May 26 13:29:18 imx8mmevk systemd[1]: edge-proxy.service: Failed with result 'exit-code'.
May 26 13:29:23 imx8mmevk systemd[1]: edge-proxy.service: Scheduled restart job, restart counter is at 9.
May 26 13:29:23 imx8mmevk systemd[1]: Stopped Tunneling Proxy for gateways.
May 26 13:29:23 imx8mmevk systemd[1]: Starting Tunneling Proxy for gateways...
May 26 13:29:23 imx8mmevk systemd[1]: Started Tunneling Proxy for gateways.
May 26 13:29:25 imx8mmevk launch-edge-proxy.sh[35445]: forwarding-addresses invalid: invalid character ':' after top-level value
May 26 13:29:25 imx8mmevk systemd[1]: edge-proxy.service: Main process exited, code=exited, status=1/FAILURE
May 26 13:29:25 imx8mmevk systemd[1]: edge-proxy.service: Failed with result 'exit-code'.```

**Comment by ygoyal18** [comment]
> I think that the last line needs some extra parentheses:
> `-forwarding-addresses={{\"gateways.local\":\"${GATEWAYS_ADDRESS#"https://"}\"},{\"containers.local\":\"${CONTAINERS_ADDRESS#"https://"}\"}}`

Thanks @petedyerarm. I will add this once we find out why PR checks are not catching the breaking change.

**Comment by ygoyal18** [comment]
Closing in favor of https://github.com/PelionIoT/meta-pelion-edge/pull/309

**Pull request closed without merging**
