### PR TITLE
Add support for imx8mmsolidrun (SD card support)

### PR DESCRIPTION
**Pull request by kivaisan**
Add support for Hummingboard Solid with booting from SD card.

Boot mode configuration: https://developer.solid-run.com/knowledge-base/hummingboard-pulse-ripple-boot-select/

Ethernet cable must be connected to CON1 -connector (closest to power connector).

For eMMC flashing device must be connected to PC from **the top most USB port** with _USB type-A to USB type-A_ OTG cable (e.g. https://www.amazon.com/gp/product/B01KRO8D20).

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
LmP v81 just went in, @esajaa merged it.
- https://github.com/PelionIoT/manifest-lmp-pelion-edge/pull/25
- https://github.com/PelionIoT/meta-pelion-edge/pull/286

**Comment by kivaisan** [comment]
Rebased. I also created a separate PR about renaming wigwag imx8mmevk changes as generic mx8mm (see pr #297).

Still to be done: Instead of deleting lmp.cfg and boot.cmd, I will create imx8solidrun versions of those to not break imx8mmevk build.

**Comment by kivaisan** [comment]
This PR is now ready for review.

**Review by JanneKiiskila — APPROVED** [review]

**Review by TapaniPuhakka — APPROVED** [review]

**Comment by kivaisan** [comment]
Added do not merge flag until Pulse/Ripple HW compatibility issues with mPCI has been resolved.

**Comment by kivaisan** [comment]
I changed this PR to use SD card as requested.

**Comment by kivaisan** [comment]
Closing this as PR checker cannot access fork. New PR: https://github.com/PelionIoT/meta-pelion-edge/pull/300

**Pull request closed without merging**
