### PR TITLE
hotfix enabling containers to inherit host's DNS and prevents a race condition

### PR DESCRIPTION
**Pull request by x85446**

### CODE REVIEW

**Review by JanneKiiskila — DISMISSED** [review]

**Review by ZakariasL — DISMISSED** [review]
LGTM

**Review by cmonr — DISMISSED** [review]
Actually, seems fine to me since its a hotfix

**Review by AnotherButler — DISMISSED** [review]

**Comment by janneblom** [comment]
> The PR tests fail because it mixes the dev branch of meta-mbed-edge with the master branch of meta-pelion-edge.

I think it is because of this fixed 'dev' for branch at repoMetaPelionEdge.groovy (from edge-ci):
`lmpPelionEdge.testCode('dev', commit_sha)`

Replacing it with `env.CHANGE_BRANCH` could work. Then it should get the correct name of the source branch of the PR.

**Comment by petedyerarm** [comment]
> > The PR tests fail because it mixes the dev branch of meta-mbed-edge with the master branch of meta-pelion-edge.
> 
> I think it is because of this fixed 'dev' for branch at repoMetaPelionEdge.groovy (from edge-ci):
> `lmpPelionEdge.testCode('dev', commit_sha)`
> 
> Replacing it with `env.CHANGE_BRANCH` could work. Then it should get the correct name of the source branch of the PR.

What does `env.CHANGE_BRANCH` contain? The PR is based upon the sha for the repo that has changed, not the other repo.

It would also be nice to somehow cover the case where we have PRs on both repos that are dependent on each other, but that might be really difficult to arrange.
There is a longer term plan to merge meta-pelion-edge and meta-mbed-edge into a single repository, which would resolve this problem.

**Comment by janneblom** [comment]
I found its explanation from here:
https://ci.eclipse.org/webtools/env-vars.html/
As it is used here in Call function:
https://github.com/PelionIoT/edge-ci/blob/master/vars/lmpPelionEdge.groovy
I got the impression it is used for this.

**Comment by x85446** [comment]
Did a git rebase -i to squash all commits.   Manually verified that this code change is exactly what QA tested.   This is ready to merge.

**Review by ygoyal18 — APPROVED** [review]

**Review by JanneKiiskila — APPROVED** [review]

**Pull request merged**
