### PR TITLE
updates golang for CVE patches and general improvements

### PR DESCRIPTION
**Pull request by x85446**

### CODE REVIEW

**Review by ygoyal18 — COMMENTED** [review]
I don't know enough about this to verify/approve it. I guess we should merge it in and test it out?

**Comment by JanneKiiskila** [comment]
@ygoyal18 - let's delay this to 2.4 release.

**Comment by JanneKiiskila** [comment]
@x85446 @ygoyal18  - please rebase, verify and then merge in.

**Comment by JanneKiiskila** [comment]
Commit shoudl explain why

`export CGO_ENABLED_riscv64 = ""`

Is needed, it doesn't make sense since we're dong Arm/Arm64/x64 targets?

**Comment by x85446** [comment]
rm-goupdate is newer and uses native golang from gatesgrath

**Pull request closed without merging**
