### PR TITLE
Introducing Fluentbit - Alternate service to process the logs and forward to Pelion cloud

### PR DESCRIPTION
**Pull request by ygoyal18**
1. Adding bbappend file to default fluentbit recipe found in meta-openembedded [here](http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-extended/fluentbit?h=dunfell)
1. Adding Fluentbit configuration - By default following input endpoints has been configured - CPU, MEM, Systemd services - edge-core, edge-proxy, pelion-relay-term, maestro, kubelet, docker and wait-for-pelion-identity, Tail - /wigwag/log/devicejs.log. The output endpoint is posting the logs at API http://gateways.local:8080/v3/device-logs (routing through edge-proxy).
1. Adding watcher service to restart Fluenbit when configuration is updated.

### CODE REVIEW

**Review by x85446 — DISMISSED** [review]

**Review by ashishwigwag — APPROVED** [review]

**Review by prakharbhatt007 — APPROVED** [review]

**Comment by ygoyal18** [comment]
@prakharbhatt007 has successfully verified it on a dev build - http://pe-jm.usa.arm.com:8080/job/rpi3.build/454/ . We had  to manually add the gateways.local to the host file for it work. Have raised the PR for that fix - #196

**Review by mohitsingalarm — APPROVED** [review]

**Comment by cmonr** [comment]
> @prakharbhatt007 has successfully verified it on a dev build - http://pe-jm.usa.arm.com:8080/job/rpi3.build/454/

@ygoyal18 Clarifying something. The above build is the nightly build for `dev`. How was this PR verified with that? I thought this recipe would need to be built and installed in order to be tested.

**Review by cmonr — CHANGES_REQUESTED** [review]
Looks good, but asked a question to better understand how this was tested.

**Comment by ygoyal18** [comment]
@cmonr Had a meeting with Mohit's team and discussed the various test cases which needs to be added to PERTS and  also  system-test inorder to validate this feature. They will take up this work in the next sprint.

**Comment by ygoyal18** [comment]
> > @prakharbhatt007 has successfully verified it on a dev build - http://pe-jm.usa.arm.com:8080/job/rpi3.build/454/
> 
> @ygoyal18 Clarifying something. The above build is the nightly build for `dev`. How was this PR verified with that? I thought this recipe would need to be built and installed in order to be tested.

We manually created the fluentbit.ipk and installed it on the nightly.dev build to verify the feature.

**Review by x85446 — APPROVED** [review]

**Review by cmonr — APPROVED** [review]

**Pull request merged**
