### PR TITLE
Introducing pe-terminal which replaces relay-term 

### PR DESCRIPTION
**Pull request by whygoyal**
pe-terminal is written in Golang. Relay-term was the only node.js-based project.
Hence, this eradicates node.js from our Yocto image.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Since the paths are now somewhat cleanly in one file, could we just change them to be /pelion instead of /wigwag @whygoyal ?

**Comment by petedyerarm** [comment]
> Since the paths are now somewhat cleanly in one file, could we just change them to be /pelion instead of /wigwag @whygoyal ?

My personal preference would be to use a more generic name, rather than that of an organisation.

**Comment by JanneKiiskila** [comment]
> My personal preference would be to use a more generic name, rather than that of an organisation.

Even more correct, yes. It should be just edge.

**Comment by whygoyal** [comment]
@JanneKiiskila as of now we do not have a folder `/pelion` on the box. In the context of pe-terminal, the actual binary is at `/wigwag/system/bin/pe-terminal` and the config file at `/wigwag/system/etc/pe-terminal/config.json`. The both locations are configurable. I can change it but not sure what all will break. Let me raise another PR to bring in that change for all the packages.

**Comment by whygoyal** [comment]
I have manually tested this and its working as expected. This is ready to be merged.

**Review by x85446 — APPROVED** [review]
lgtm

**Comment by JanneKiiskila** [comment]
We need to be mindful of the folders that are OK from OSTree point of view.

**Pull request merged**
