### PR TITLE
Change default Node IP to link local

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Seems the default 10.0.0.50 will overlap easily with routers that
use the 10.0.0.x address space as the default address space.

A customer ran into this problem and thus we should avoid using
(by default) something that is likely to conflict.

Internal ref; https://armiot.atlassian.net/browse/IOTNGGW-261

### CODE REVIEW

**Comment by TapaniPuhakka** [comment]
I was wondering could we just define this network with /32 prefix so nothing else would ever get routed there than this specific address. 

Then only problem would be this specific address would be non reachable outside the device if it is used in the actual network.

(Just wondered should we go to something nasty like defining network address to be something else than 10.x.x.x like some random 11.x.x.x with /32 prefix, would that then work and have very unlikely to cause problems ?.)

**Comment by TapaniPuhakka** [comment]
Also idea Kevin proposed of using link local address  sounds like a solution.  (169.254.0.0/16 )
https://en.wikipedia.org/wiki/Link-local_address

**Comment by ZakariasL** [comment]
10.239.0.128 sounds good to me, in terms of KaaS any available IP will work.

I agree that we should reduce the subnet and I believe /32 should be ok. The Kubernetes node will get assigned this IP and since all communication with the Node goes through edge-proxy, I don't think it needs to be reachable from other devices on the network. @sk-arm do you see any problem with using a /32 subnet for the kaas0 interface?

**Comment by JanneKiiskila** [comment]
Force pushed in the link local address now.

**Comment by JanneKiiskila** [comment]
What about the other ones then @sk-arm  @ZakariasL ?

```
EDGE_PODCIDR = "10.240.0.0/24"
EDGE_PODCIDR_GW = "10.240.0.1"
```

**Comment by JanneKiiskila** [comment]
2nd commit resolves that issue, pods can also use link local addresses. Great!

**Comment by JanneKiiskila** [comment]
Does https://github.com/PelionIoT/meta-pelion-edge/blob/8b6b67c16969f3045f532b2c94363e69e5d3766f/recipes-containers/kubelet/files/kubelet-config.yaml the contents of that have to match also this?

**Comment by JanneKiiskila** [comment]
@ZakariasL  will raise a new PR.

**Comment by JanneKiiskila** [comment]
Proper PR in https://github.com/PelionIoT/meta-pelion-edge/pull/356

**Pull request closed without merging**
